# Generates a SELF-DESCRIBING Kamal deploy artifact for an app (ADR 0001).
#
# Kamal 2 does NOT inject env or secrets into config/deploy.yml ERB (Handbook §8.1),
# so real deploy coordinates must be written as literal values — not ENV[...] ||
# placeholder fallbacks whose truth lives only in Conductor's DB. We emit a Kamal
# *destination overlay* so the app's base config is untouched:
#
#   config/deploy.production.yml  — real host/service/proxy/registry + env split
#   .kamal/secrets.production     — git-safe secret POINTERS (localvault / master.key)
#
# Acceptance (ADR 0001): with the repo + an authorized SSH key an operator runs
#   kamal console -d production   /   kamal app logs -d production
# against real prod WITHOUT querying Conductor.
class KamalConfig
  DESTINATION = "production".freeze

  # Keys that ARE the deploy coordinates — represented structurally below, so they
  # don't also leak into env.clear.
  DEPLOY_KEYS = %w[
    KAMAL_SERVICE DEPLOY_SERVER_IP DEPLOY_SSH_USER APP_HOST
    KAMAL_REGISTRY_SERVER KAMAL_REGISTRY_USERNAME KAMAL_REGISTRY_PASSWORD
  ].freeze

  attr_reader :app, :vault

  def initialize(app, vault: nil)
    @app = app
    # localvault vault holding this app's secrets. Convention: key = <slug>.<KEY>.
    @vault = vault.presence || "devops"
  end

  # The real, literal destination overlay (config/deploy.production.yml).
  def deploy_overlay_yaml
    overlay = {
      "service" => app.slug,
      "image"   => "#{registry_username}/#{app.slug}",
      "servers" => { "web" => [app.server&.ip_address].compact },
      "ssh"     => { "user" => app.server&.ssh_user_or_default || "deploy" },
      "proxy"   => proxy_block,
      "registry" => {
        "server"   => registry_server,
        "username" => registry_username,
        "password" => ["KAMAL_REGISTRY_PASSWORD"]
      },
      "env" => env_block
    }.compact

    header + YAML.dump(overlay).sub(/\A---\n/, "")
  end

  # The git-safe secrets file (.kamal/secrets.production). No raw values — secrets
  # resolve from the ENVIRONMENT (variable substitution), which Conductor injects
  # at deploy time and an operator seeds ONCE for hand use. The header documents
  # the localvault seed so it isn't needed on every command ("seed once").
  def secrets_file
    all_keys = (["KAMAL_REGISTRY_PASSWORD"] + secret_keys).uniq - ["RAILS_MASTER_KEY"]

    header = ["# #{GENERATED} — .kamal/secrets.#{DESTINATION}",
              "# Git-safe: values are NOT here. Conductor injects these at deploy time.",
              "# For hand use (kamal console -d #{DESTINATION}), seed your env ONCE, e.g.:",
              "#   localvault unlock #{vault}"]
    all_keys.each { |k| header << "#   export #{k}=$(localvault get #{app.slug}.#{k} --vault #{vault})" }

    body = all_keys.map { |k| "#{k}=$#{k}" }
    body << "RAILS_MASTER_KEY=$(cat config/master.key)" if secret_keys.include?("RAILS_MASTER_KEY") || app.env_hash.key?("RAILS_MASTER_KEY")

    (header + [""] + body).join("\n") + "\n"
  end

  # Path => contents, for a writer to drop into a checkout (or commit to the repo).
  def files
    {
      "config/deploy.#{DESTINATION}.yml"  => deploy_overlay_yaml,
      ".kamal/secrets.#{DESTINATION}"     => secrets_file
    }
  end

  private

  GENERATED = "Generated by Conductor (self-describing deploy, ADR 0001)".freeze

  def header
    "# #{GENERATED}\n" \
    "# Real deploy coordinates for #{app.name}. Reproducible by hand:\n" \
    "#   kamal console -d #{DESTINATION}   /   kamal app logs -d #{DESTINATION}\n"
  end

  def proxy_block
    return nil if app.domain.blank?
    { "ssl" => !!app.ssl_enabled, "host" => app.domain, "app_port" => app.port || 3000 }.compact
  end

  def env_block
    block = {}
    clear = app.env_variables.visible.reject { |v| DEPLOY_KEYS.include?(v.key) }
                .to_h { |v| [v.key, v.value] }
    block["clear"]  = clear if clear.any?
    block["secret"] = secret_keys if secret_keys.any?
    block.presence
  end

  def secret_keys
    @secret_keys ||= app.deploy_secret_keys.reject { |k| DEPLOY_KEYS.include?(k) }.sort
  end

  def registry_server
    # Kamal's default registry is Docker Hub; apps using another registry set
    # KAMAL_REGISTRY_SERVER explicitly. Default here must match Kamal's default.
    app.env_hash["KAMAL_REGISTRY_SERVER"].presence || "docker.io"
  end

  def registry_username
    app.env_hash["KAMAL_REGISTRY_USERNAME"].presence || "REGISTRY_USERNAME"
  end
end
