# frozen_string_literal: true

# ==============================================================================
# RapidRailsUI Tailwind v4 Integration Initializer
# ==============================================================================
#
# WHY THIS FILE EXISTS:
# ---------------------
# Tailwind v4 needs to know WHERE to find the RapidRailsUI gem's component files
# to scan them for Tailwind class names. The gem's location can change between
# development and production, or when updating the gem version.
#
# WHAT IT DOES:
# -------------
# On every Rails boot, this initializer:
# 1. Finds the current location of the rapid_rails_ui gem
# 2. Updates the @source paths in app/assets/tailwind/application.css
# 3. Ensures Tailwind can always find and scan the gem's components
#
# FOR TAILWIND v3 USERS:
# ----------------------
# This file does nothing. Tailwind v3 uses tailwind.config.js instead,
# which is configured once during installation.
#
# DO NOT EDIT THIS FILE - it regenerates paths automatically.
# ==============================================================================

Rails.application.config.after_initialize do
  # Only generate for Tailwind v4 (which uses @source directives)
  tailwind_css_path = Rails.root.join("app/assets/tailwind/application.css")

  # Skip if Tailwind v3 (uses config.js instead)
  next unless File.exist?(tailwind_css_path)

  content = File.read(tailwind_css_path)
  next unless content.include?("@import") && content.include?("tailwindcss")

  # Only proceed if application.css already has our marker comment
  next unless content.include?("RapidRailsUI gem components")

  begin
    # Get the gem paths dynamically
    gem_spec = Gem::Specification.find_by_name("rapid_rails_ui")
    gem_components_path = File.join(gem_spec.gem_dir, "app/components/**/*.{rb,erb,js}")
    gem_helpers_path = File.join(gem_spec.gem_dir, "lib/rapid_rails_ui/helpers/**/*.{rb,erb}")

    # Update the @source paths in application.css (need both components and helpers)
    updated_content = content.gsub(
      /@source\s+"[^"]*rapid_rails_ui\/app\/components[^"]*";/,
      "@source \"#{gem_components_path}\";"
    ).gsub(
      /@source\s+"[^"]*rapid_rails_ui\/lib\/rapid_rails_ui\/helpers[^"]*";/,
      "@source \"#{gem_helpers_path}\";"
    )

    if updated_content != content
      File.write(tailwind_css_path, updated_content)
      Rails.logger.info "✅ RapidRailsUI: Updated Tailwind @source paths"
      Rails.logger.debug "   Components: #{gem_components_path}"
      Rails.logger.debug "   Helpers: #{gem_helpers_path}"
    end
  rescue Gem::MissingSpecException
    # Development mode with path gem - try Bundler
    begin
      spec = Bundler.load.specs.find { |s| s.name == "rapid_rails_ui" }
      if spec
        gem_components_path = File.join(spec.full_gem_path, "app/components/**/*.{rb,erb,js}")
        gem_helpers_path = File.join(spec.full_gem_path, "lib/rapid_rails_ui/helpers/**/*.{rb,erb}")

        updated_content = content.gsub(
          /@source\s+"[^"]*rapid_rails_ui\/app\/components[^"]*";/,
          "@source \"#{gem_components_path}\";"
        ).gsub(
          /@source\s+"[^"]*rapid_rails_ui\/lib\/rapid_rails_ui\/helpers[^"]*";/,
          "@source \"#{gem_helpers_path}\";"
        )

        if updated_content != content
          File.write(tailwind_css_path, updated_content)
          Rails.logger.info "✅ RapidRailsUI: Updated Tailwind @source paths (development mode)"
          Rails.logger.debug "   Components: #{gem_components_path}"
          Rails.logger.debug "   Helpers: #{gem_helpers_path}"
        end
      end
    rescue => e
      Rails.logger.warn "⚠️  RapidRailsUI: Could not update Tailwind @source paths: #{e.message}"
      Rails.logger.warn "   This is expected if using Tailwind v3 or if the gem isn't installed yet."
      Rails.logger.warn "   If using Tailwind v4, you may need to manually update @source paths in app/assets/tailwind/application.css"
    end
  end
end
